/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import databaserunner.*;
import javax.swing.*;
import java.awt.event.*;

public class SimulateReaction extends javax.swing.JFrame implements WindowListener{

    //Our Fields
    private Element reactant1;
    private Element reactant2;
    private BinaryCompound product;
    
    private Reaction reaction;
    
    private boolean sameReactants;
    private boolean productInfoEntered;
    private boolean noProduct;
    
    private DatabaseGUI databaseGUI;
 
    //Constructor
    public SimulateReaction(DatabaseGUI databaseGUI) {
        this.databaseGUI = databaseGUI;
        this.sameReactants = false;
        this.noProduct = true;
        this.productInfoEntered = false;
        initComponents();
        this.setComponentsEnabled(false);
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        if (DatabaseGUI.getMadeChanges()) {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            this.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    databaseGUI.savePrompt(true);
                }
            });
        }
    }
    
    //Our methods
    
    public void setComponentsEnabled(boolean enabled) {
        this.jButtonSubmitProductProperties.setEnabled(enabled);
        this.jButtonTryAnother.setEnabled(enabled);
        this.setProductTextFieldsEnabled(enabled);
    };
    
    public void setProductTextFieldsEnabled(boolean enabled) {
        this.jTextFieldProductName.setEnabled(enabled);
        this.jTextFieldProductDensity.setEnabled(enabled);
        this.jTextFieldProductBP.setEnabled(enabled);
        this.jTextFieldProductMP.setEnabled(enabled);
        this.jTextFieldProductColour.setEnabled(enabled);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabelReactant1 = new javax.swing.JLabel();
        jLabelReactant2 = new javax.swing.JLabel();
        jLabelProduct = new javax.swing.JLabel();
        jLabelEquation = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonSubmitReactants = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jTextFieldReactant1 = new javax.swing.JTextField();
        jTextFieldReactant2 = new javax.swing.JTextField();
        jButtonTryAnother = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelEquationPlus = new javax.swing.JLabel();
        jLabelEquationArrow = new javax.swing.JLabel();
        jLabelEquationProductA = new javax.swing.JLabel();
        jLabelProductName = new javax.swing.JLabel();
        jLabelProductMolarMass = new javax.swing.JLabel();
        jLabelProductStpState = new javax.swing.JLabel();
        jLabelProductStpDensity = new javax.swing.JLabel();
        jLabelProductMP = new javax.swing.JLabel();
        jLabelProductBP = new javax.swing.JLabel();
        jLabelProductColour = new javax.swing.JLabel();
        jLabelProductCharge = new javax.swing.JLabel();
        jTextFieldProductName = new javax.swing.JTextField();
        jLabelEquationReactant2 = new javax.swing.JLabel();
        jLabelEquationReactant1 = new javax.swing.JLabel();
        jLabelEquationProductB = new javax.swing.JLabel();
        jLabelEquationProductSubscriptA = new javax.swing.JLabel();
        jLabelEquationProductSubscriptB = new javax.swing.JLabel();
        jLabelMolecularFormulaReactant1 = new javax.swing.JLabel();
        jLabelProtonsReactant1 = new javax.swing.JLabel();
        jLabelMassReactant1 = new javax.swing.JLabel();
        jLabelProductSubscriptB = new javax.swing.JLabel();
        jLabelProductA = new javax.swing.JLabel();
        jLabelProductB = new javax.swing.JLabel();
        jLabelProductSubscriptA = new javax.swing.JLabel();
        jLabelOxNumReactant1 = new javax.swing.JLabel();
        jLabelMolecularFormulaReactant2 = new javax.swing.JLabel();
        jLabelProtonsReactant2 = new javax.swing.JLabel();
        jLabelMassReactant2 = new javax.swing.JLabel();
        jLabelOxNumReactant2 = new javax.swing.JLabel();
        jButtonSubmitProductProperties = new javax.swing.JButton();
        jLabelEquationProductCharge = new javax.swing.JLabel();
        jTextFieldProductDensity = new javax.swing.JTextField();
        jTextFieldProductColour = new javax.swing.JTextField();
        jTextFieldProductBP = new javax.swing.JTextField();
        jTextFieldProductMP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 690));

        jLabelReactant1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelReactant1.setText("Reactant 1");

        jLabelReactant2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelReactant2.setText("Reactant 2");

        jLabelProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelProduct.setText("Product");

        jLabelEquation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEquation.setText("Overall Equation:");

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Simulate Reaction");

        jButtonSubmitReactants.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSubmitReactants.setText("SUBMIT");
        jButtonSubmitReactants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitReactantsActionPerformed(evt);
            }
        });

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInfo.setText("Please specify names of elements for reactants");

        jTextFieldReactant1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldReactant1.setText("Enter Name Here");

        jTextFieldReactant2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldReactant2.setText("Enter Name Here");

        jButtonTryAnother.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonTryAnother.setText("Try Another");
        jButtonTryAnother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTryAnotherActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelEquationPlus.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelEquationPlus.setText("+");

        jLabelEquationArrow.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelEquationArrow.setText("→");

        jLabelEquationProductA.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelEquationProductA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationProductA.setText("A");

        jLabelProductName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductName.setText("Name:");

        jLabelProductMolarMass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductMolarMass.setText("Molar Mass:");

        jLabelProductStpState.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductStpState.setText("State @ STP:");

        jLabelProductStpDensity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductStpDensity.setText("Density @ STP:");

        jLabelProductMP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductMP.setText("Melting Point:");

        jLabelProductBP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductBP.setText("Boiling Point:");

        jLabelProductColour.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductColour.setText("Colour: ");

        jLabelProductCharge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProductCharge.setText("[Charge]");

        jLabelEquationReactant2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelEquationReactant2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationReactant2.setText("B");

        jLabelEquationReactant1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelEquationReactant1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationReactant1.setText("A");

        jLabelEquationProductB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelEquationProductB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationProductB.setText("B");

        jLabelEquationProductSubscriptA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEquationProductSubscriptA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationProductSubscriptA.setText("a");

        jLabelEquationProductSubscriptB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEquationProductSubscriptB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationProductSubscriptB.setText("b");

        jLabelMolecularFormulaReactant1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMolecularFormulaReactant1.setText("A");

        jLabelProtonsReactant1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProtonsReactant1.setText("[Protons]");

        jLabelMassReactant1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMassReactant1.setText("[Mass Number]");

        jLabelProductSubscriptB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelProductSubscriptB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductSubscriptB.setText("b");

        jLabelProductA.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelProductA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductA.setText("A");

        jLabelProductB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelProductB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductB.setText("B");

        jLabelProductSubscriptA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelProductSubscriptA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductSubscriptA.setText("a");

        jLabelOxNumReactant1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelOxNumReactant1.setText("[Oxidation #]");

        jLabelMolecularFormulaReactant2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMolecularFormulaReactant2.setText("B");

        jLabelProtonsReactant2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProtonsReactant2.setText("[Protons]");

        jLabelMassReactant2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMassReactant2.setText("[Mass Number]");

        jLabelOxNumReactant2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelOxNumReactant2.setText("[Oxidation #]");

        jButtonSubmitProductProperties.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSubmitProductProperties.setText("SUBMIT");
        jButtonSubmitProductProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitProductPropertiesActionPerformed(evt);
            }
        });

        jLabelEquationProductCharge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEquationProductCharge.setText("[Charge]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelEquation)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProductA)
                                .addGap(4, 4, 4)
                                .addComponent(jLabelProductSubscriptA)
                                .addGap(3, 3, 3)
                                .addComponent(jLabelProductB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelProductSubscriptB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelProductCharge))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProductName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelProductMolarMass)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProductStpDensity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProductDensity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProductColour)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSubmitProductProperties)
                                    .addComponent(jTextFieldProductColour))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProductMP)
                                .addGap(5, 5, 5)
                                .addComponent(jTextFieldProductBP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelProductStpState)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProductBP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProductMP, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabelEquationReactant1)
                        .addGap(49, 49, 49)
                        .addComponent(jLabelEquationPlus)
                        .addGap(68, 68, 68)
                        .addComponent(jLabelEquationReactant2)
                        .addGap(50, 50, 50)
                        .addComponent(jLabelEquationArrow)
                        .addGap(54, 54, 54)
                        .addComponent(jLabelEquationProductA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEquationProductSubscriptA)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelEquationProductB)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEquationProductSubscriptB))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabelEquationProductCharge))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabelProduct))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabelReactant1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jTextFieldReactant1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelProtonsReactant1)
                                    .addComponent(jLabelMassReactant1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelMolecularFormulaReactant1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelOxNumReactant1)))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldReactant2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelProtonsReactant2)
                                    .addComponent(jLabelMassReactant2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelMolecularFormulaReactant2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelOxNumReactant2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelReactant2)
                                .addGap(59, 59, 59))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTitle)
                                .addGap(138, 138, 138)
                                .addComponent(jButtonBack))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSubmitReactants)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelInfo)
                                .addGap(181, 181, 181)
                                .addComponent(jButtonTryAnother)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jButtonBack))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelReactant1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldReactant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelMolecularFormulaReactant1)
                                .addComponent(jLabelMassReactant1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelOxNumReactant1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabelProtonsReactant1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelReactant2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldReactant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelMolecularFormulaReactant2)
                                .addComponent(jLabelMassReactant2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelOxNumReactant2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabelProtonsReactant2))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubmitReactants)
                    .addComponent(jLabelInfo)
                    .addComponent(jButtonTryAnother))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelProduct)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabelProductMolarMass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelProductStpDensity)
                                    .addComponent(jTextFieldProductDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabelProductA)
                                                .addComponent(jLabelProductB))
                                            .addGap(4, 4, 4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabelProductSubscriptB)
                                                .addComponent(jLabelProductSubscriptA))))
                                    .addComponent(jLabelProductCharge))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProductColour)
                            .addComponent(jTextFieldProductColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelProductName)
                            .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jButtonSubmitProductProperties)
                        .addGap(23, 23, 23)
                        .addComponent(jLabelEquation))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelProductStpState)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProductBP)
                            .addComponent(jTextFieldProductMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProductMP)
                            .addComponent(jTextFieldProductBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelEquationProductB)
                                    .addGap(4, 4, 4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelEquationProductSubscriptB)
                                        .addComponent(jLabelEquationProductSubscriptA)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelEquationProductCharge)
                            .addGap(37, 37, 37)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEquationPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEquationArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEquationProductA)
                        .addComponent(jLabelEquationReactant2)
                        .addComponent(jLabelEquationReactant1)))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        if(this.productInfoEntered || this.noProduct){
            this.databaseGUI.startHomePage();
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Please name your product!");
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSubmitReactantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitReactantsActionPerformed
        this.jButtonTryAnother.setEnabled(true);
        this.jButtonSubmitReactants.setEnabled(false);
        this.jTextFieldReactant1.setEnabled(false);
        this.jTextFieldReactant2.setEnabled(false);
        
        Chemical tempChemical1 = this.databaseGUI.searchChemicalsByName(this.jTextFieldReactant1.getText());
        Chemical tempChemical2 = this.databaseGUI.searchChemicalsByName(this.jTextFieldReactant2.getText());
        
        if (tempChemical1 instanceof Element && tempChemical2 instanceof Element) {
            this.reactant1 = (Element)tempChemical1;
            this.reactant2 = (Element)tempChemical2;
            
            if (this.reactant1 == this.reactant2)
                this.sameReactants = true;
            
            //Reactant 1
            this.jLabelMassReactant1.setText("" + (this.reactant1.getNumProton() + this.reactant1.getNumNeutron()));
            this.jLabelProtonsReactant1.setText("" + this.reactant1.getNumProton());
            this.jLabelMolecularFormulaReactant1.setText(this.reactant1.getAtomicSymbol());
            this.jLabelOxNumReactant1.setText("" + this.reactant1.getOxidationNum());
            
            //Reactant 2
            this.jLabelMassReactant2.setText("" + (this.reactant2.getNumProton() + this.reactant1.getNumNeutron()));
            this.jLabelProtonsReactant2.setText("" + this.reactant2.getNumProton());
            this.jLabelMolecularFormulaReactant2.setText(this.reactant2.getAtomicSymbol());
            this.jLabelOxNumReactant2.setText("" + this.reactant2.getOxidationNum());
            
            this.reaction = this.databaseGUI.simulateReaction(this.reactant1, this.reactant2);
  
            if (this.reaction.getID() == Reaction.getREPEATED_REACTION_ID()) {
                JOptionPane.showMessageDialog(null, "Reaction already exists!");
            } else if (this.reaction.getID() == Reaction.getIMPOSSIBLE_REACTION_ID()) {
                JOptionPane.showMessageDialog(null, "Reaction not possible!");
            } else {
                JOptionPane.showMessageDialog(null, "New reaction successful!");
                
                this.jButtonSubmitProductProperties.setEnabled(true);
                this.setProductTextFieldsEnabled(true);
                this.noProduct = false;

                this.product = this.reaction.getProduct();
                
                //Check if Reactants are the same
                if (!this.sameReactants) {
                    //Product Formulas
                    this.jLabelProductA.setText(this.product.getComponent1().getComponent().getAtomicSymbol());
                    this.jLabelProductB.setText(this.product.getComponent2().getComponent().getAtomicSymbol());
                    this.jLabelEquationProductA.setText(this.product.getComponent1().getComponent().getAtomicSymbol());
                    this.jLabelEquationProductB.setText(this.product.getComponent2().getComponent().getAtomicSymbol());

                    //Subscripts
                    if (this.product.getComponent1().getNumOccurrence() > 1) {
                        this.jLabelProductSubscriptA.setText("" + this.product.getComponent1().getNumOccurrence());
                        this.jLabelEquationProductSubscriptA.setText("" + this.product.getComponent1().getNumOccurrence());
                    } else {
                        this.jLabelProductSubscriptA.setText("");
                        this.jLabelEquationProductSubscriptA.setText("");
                    }
                    if (this.product.getComponent2().getNumOccurrence() > 1) {
                        this.jLabelProductSubscriptB.setText("" + this.product.getComponent2().getNumOccurrence());
                        this.jLabelEquationProductSubscriptB.setText("" + this.product.getComponent2().getNumOccurrence());
                    } else {
                        this.jLabelProductSubscriptB.setText("");
                        this.jLabelEquationProductSubscriptB.setText("");
                    }
                } else {
                    this.jLabelProductA.setText("");
                    this.jLabelProductSubscriptA.setText("");
                    this.jLabelEquationProductA.setText("");
                    this.jLabelEquationProductSubscriptA.setText("");
                    
                    this.jLabelProductB.setText(this.product.getComponent2().getComponent().getAtomicSymbol());
                    this.jLabelProductSubscriptB.setText("" + (this.product.getComponent1().getNumOccurrence() + this.product.getComponent2().getNumOccurrence()));
                    this.jLabelEquationProductB.setText(this.product.getComponent2().getComponent().getAtomicSymbol());
                    this.jLabelEquationProductSubscriptB.setText("" + (this.product.getComponent1().getNumOccurrence() + this.product.getComponent2().getNumOccurrence()));
                }
                
                //Reactants in Equation
                this.jLabelEquationReactant1.setText(this.reactant1.getAtomicSymbol());
                this.jLabelEquationReactant2.setText(this.reactant2.getAtomicSymbol());
                
                //Product Properties
                this.jLabelProductMolarMass.setText("Molar Mass: " + this.product.getMolarMass());
                
                if (this.product.getStpState() == Chemical.DEFAULT_STATE)
                    this.jLabelProductStpState.setText("State @ STP: " + Chemical.DEFAULT_COMMON_NAME);
                else
                    this.jLabelProductStpState.setText("State @ STP: " + this.product.getStpState());
                
                //Set Charges for both
                int charge = this.product.getCharge();
                if (charge != 0) {
                    if (charge > 0) {
                        this.jLabelProductCharge.setText("+" + charge);
                        this.jLabelEquationProductCharge.setText("+" + charge);
                    } else {
                        this.jLabelProductCharge.setText("" + charge);
                        this.jLabelEquationProductCharge.setText("" + charge);
                    }
                } else {
                    this.jLabelProductCharge.setText("");
                    this.jLabelEquationProductCharge.setText("");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Reactant not found!");
        }
    }//GEN-LAST:event_jButtonSubmitReactantsActionPerformed

    private void jButtonTryAnotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTryAnotherActionPerformed
        if(this.productInfoEntered || this.noProduct){
            this.noProduct = true;
            this.productInfoEntered = false;

            this.jButtonTryAnother.setEnabled(false);
            this.jButtonSubmitReactants.setEnabled(true);
            this.jButtonSubmitProductProperties.setEnabled(false);
            this.setProductTextFieldsEnabled(false);
            this.jTextFieldReactant1.setEnabled(true);
            this.jTextFieldReactant2.setEnabled(true);

            this.sameReactants = false;

            this.jTextFieldReactant1.setText("Enter Name Here");
            this.jLabelMassReactant1.setText("[Mass Number]");
            this.jLabelProtonsReactant1.setText("[Protons]");
            this.jLabelOxNumReactant1.setText("[Oxidation #]");
            this.jLabelMolecularFormulaReactant1.setText("A");

            this.jTextFieldReactant2.setText("Enter Name Here");
            this.jLabelMassReactant2.setText("[Mass Number]");
            this.jLabelProtonsReactant2.setText("[Protons]");
            this.jLabelOxNumReactant2.setText("[Oxidation #]");
            this.jLabelMolecularFormulaReactant2.setText("B");

            this.jTextFieldProductName.setText("");
            this.jTextFieldProductDensity.setText("");
            this.jTextFieldProductBP.setText("");
            this.jTextFieldProductMP.setText("");
            this.jTextFieldProductColour.setText("");
            this.jLabelProductMolarMass.setText("Molar Mass: ");
            this.jLabelProductStpDensity.setText("Density @ STP: ");
            this.jLabelProductStpState.setText("State @ STP: ");
            this.jLabelProductMP.setText("Melting Point: ");
            this.jLabelProductBP.setText("Boiling Point: ");
            this.jLabelProductColour.setText("Colour: ");
            this.jLabelProductA.setText("A");
            this.jLabelProductSubscriptA.setText("a");
            this.jLabelProductB.setText("B");
            this.jLabelProductSubscriptB.setText("b");
            this.jLabelProductCharge.setText("[Charge]");

            this.jLabelEquationReactant1.setText("A");
            this.jLabelEquationReactant2.setText("B");
            this.jLabelEquationProductA.setText("A");
            this.jLabelEquationProductB.setText("B");
            this.jLabelEquationProductSubscriptA.setText("a");
            this.jLabelEquationProductSubscriptB.setText("b");
            this.jLabelEquationProductCharge.setText("[Charge]");
        }else
            JOptionPane.showMessageDialog(null, "Please name your product!");
    }//GEN-LAST:event_jButtonTryAnotherActionPerformed

    private void jButtonSubmitProductPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitProductPropertiesActionPerformed
        String commonName; 
        double bp;
        double mp;
        double density;
        String colour;
        
        try {
            //read required fields
            commonName = jTextFieldProductName.getText();
            
            //read optional fields
            if (!this.jTextFieldProductDensity.getText().equals(DatabaseGUI.EMPTY_STRING))
                density = Double.parseDouble(this.jTextFieldProductDensity.getText());
            else
                density = Chemical.getDEFAULT_DENSITY();
            
            if (!this.jTextFieldProductBP.getText().equals(DatabaseGUI.EMPTY_STRING))
                bp = Double.parseDouble(this.jTextFieldProductBP.getText());
            else
                bp = Chemical.getDEFAULT_STATE_CHANGE_TEMP();
            
            if (!this.jTextFieldProductMP.getText().equals(DatabaseGUI.EMPTY_STRING))
                mp = Double.parseDouble(this.jTextFieldProductMP.getText());
            else
                mp = Chemical.getDEFAULT_STATE_CHANGE_TEMP();
            
            if (!this.jTextFieldProductColour.getText().equals(DatabaseGUI.EMPTY_STRING))
                colour = this.jTextFieldProductColour.getText();
            else
                colour = Chemical.getDEFAULT_COLOUR();
            
            //create temp BinaryCompound
            BinaryCompound newBinaryCompound = new BinaryCompound();
            
            //check fields
            if(commonName.equals(DatabaseGUI.EMPTY_STRING))
                JOptionPane.showMessageDialog(null, "A required field is blank!");
            
            else if(!newBinaryCompound.setCommonName(commonName))
                JOptionPane.showMessageDialog(null, "Illegal name!");
            
            else if(!newBinaryCompound.setStpDensity(density))
                JOptionPane.showMessageDialog(null, "Illegal density!");
            
            else if(!newBinaryCompound.setBP(bp))
                JOptionPane.showMessageDialog(null, "Illegal boiling point!");
            
            else if(!newBinaryCompound.setMP(mp))
                JOptionPane.showMessageDialog(null, "Illegal melting point!");
            
            else if (this.databaseGUI.editBinaryCompounds(this.product, commonName, density, bp, mp, colour)) {
                this.product = (BinaryCompound)this.databaseGUI.searchChemicalsByName(commonName);
                this.jLabelProductStpState.setText("State @ STP: " + this.product.getStpState());
                this.productInfoEntered = true;
                JOptionPane.showMessageDialog(null, "Properties set successfully!"); 
                
            }else
                JOptionPane.showMessageDialog(null, "A chemical with that information already exists!");
            
        } catch(NumberFormatException nfx) {
            JOptionPane.showMessageDialog(null, "Erroneous data has been entered!");
        }
    }//GEN-LAST:event_jButtonSubmitProductPropertiesActionPerformed

    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulateReaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulateReaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulateReaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulateReaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulateReaction(databaseGUI).setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSubmitProductProperties;
    private javax.swing.JButton jButtonSubmitReactants;
    private javax.swing.JButton jButtonTryAnother;
    private javax.swing.JLabel jLabelEquation;
    private javax.swing.JLabel jLabelEquationArrow;
    private javax.swing.JLabel jLabelEquationPlus;
    private javax.swing.JLabel jLabelEquationProductA;
    private javax.swing.JLabel jLabelEquationProductB;
    private javax.swing.JLabel jLabelEquationProductCharge;
    private javax.swing.JLabel jLabelEquationProductSubscriptA;
    private javax.swing.JLabel jLabelEquationProductSubscriptB;
    private javax.swing.JLabel jLabelEquationReactant1;
    private javax.swing.JLabel jLabelEquationReactant2;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelMassReactant1;
    private javax.swing.JLabel jLabelMassReactant2;
    private javax.swing.JLabel jLabelMolecularFormulaReactant1;
    private javax.swing.JLabel jLabelMolecularFormulaReactant2;
    private javax.swing.JLabel jLabelOxNumReactant1;
    private javax.swing.JLabel jLabelOxNumReactant2;
    private javax.swing.JLabel jLabelProduct;
    private javax.swing.JLabel jLabelProductA;
    private javax.swing.JLabel jLabelProductB;
    private javax.swing.JLabel jLabelProductBP;
    private javax.swing.JLabel jLabelProductCharge;
    private javax.swing.JLabel jLabelProductColour;
    private javax.swing.JLabel jLabelProductMP;
    private javax.swing.JLabel jLabelProductMolarMass;
    private javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelProductStpDensity;
    private javax.swing.JLabel jLabelProductStpState;
    private javax.swing.JLabel jLabelProductSubscriptA;
    private javax.swing.JLabel jLabelProductSubscriptB;
    private javax.swing.JLabel jLabelProtonsReactant1;
    private javax.swing.JLabel jLabelProtonsReactant2;
    private javax.swing.JLabel jLabelReactant1;
    private javax.swing.JLabel jLabelReactant2;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldProductBP;
    private javax.swing.JTextField jTextFieldProductColour;
    private javax.swing.JTextField jTextFieldProductDensity;
    private javax.swing.JTextField jTextFieldProductMP;
    private javax.swing.JTextField jTextFieldProductName;
    private javax.swing.JTextField jTextFieldReactant1;
    private javax.swing.JTextField jTextFieldReactant2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosing(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosed(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}