/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import databaserunner.*;
import javax.swing.*;

/**
 *
 * @author Daniel
 */
public class SimulateReaction extends javax.swing.JFrame {

    //Our Fields
    private static int id;
    private static Element reactant1;
    private static Element reactant2;
    private static BinaryCompound product;
    
    private static Reaction reaction;
    
    private static boolean sameReactants;
    private static boolean nameEntered;
    private static boolean noProduct;
 
    //Constructor
    public SimulateReaction() {
        initComponents();
        init();
    }
    
    //Our methods
    
    public void init() {
        this.jButtonSubmitProductName.setEnabled(false);
        this.jButtonTryAnother.setEnabled(false);
        noProduct = true;
        nameEntered = false;
    };
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabelReactant1 = new javax.swing.JLabel();
        jLabelReactant2 = new javax.swing.JLabel();
        jLabelProduct = new javax.swing.JLabel();
        jLabelEquation = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonSubmitReactants = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jTextFieldReactant1 = new javax.swing.JTextField();
        jTextFieldReactant2 = new javax.swing.JTextField();
        jButtonTryAnother = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelEquationPlus = new javax.swing.JLabel();
        jLabelEquationArrow = new javax.swing.JLabel();
        jLabelEquationProductA = new javax.swing.JLabel();
        jLabelProductName = new javax.swing.JLabel();
        jLabelProductMolarMass = new javax.swing.JLabel();
        jLabelProductStpState = new javax.swing.JLabel();
        jLabelProductStpDensity = new javax.swing.JLabel();
        jLabelProductMP = new javax.swing.JLabel();
        jLabelProductBP = new javax.swing.JLabel();
        jLabelProductColour = new javax.swing.JLabel();
        jLabelProductCharge = new javax.swing.JLabel();
        jTextFieldProductName = new javax.swing.JTextField();
        jLabelEquationReactant2 = new javax.swing.JLabel();
        jLabelEquationReactant1 = new javax.swing.JLabel();
        jLabelEquationProductB = new javax.swing.JLabel();
        jLabelEquationProductSubscriptA = new javax.swing.JLabel();
        jLabelEquationProductSubscriptB = new javax.swing.JLabel();
        jLabelMolecularFormulaReactant1 = new javax.swing.JLabel();
        jLabelProtonsReactant1 = new javax.swing.JLabel();
        jLabelMassReactant1 = new javax.swing.JLabel();
        jLabelProductSubscriptB = new javax.swing.JLabel();
        jLabelProductA = new javax.swing.JLabel();
        jLabelProductB = new javax.swing.JLabel();
        jLabelProductSubscriptA = new javax.swing.JLabel();
        jLabelOxNumReactant1 = new javax.swing.JLabel();
        jLabelMolecularFormulaReactant2 = new javax.swing.JLabel();
        jLabelProtonsReactant2 = new javax.swing.JLabel();
        jLabelMassReactant2 = new javax.swing.JLabel();
        jLabelOxNumReactant2 = new javax.swing.JLabel();
        jButtonSubmitProductName = new javax.swing.JButton();
        jLabelEquationProductCharge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 650));

        jLabelReactant1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelReactant1.setText("Reactant 1");

        jLabelReactant2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelReactant2.setText("Reactant 2");

        jLabelProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelProduct.setText("Product");

        jLabelEquation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEquation.setText("Overall Equation:");

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Simulate Reaction");

        jButtonSubmitReactants.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSubmitReactants.setText("SUBMIT");
        jButtonSubmitReactants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitReactantsActionPerformed(evt);
            }
        });

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInfo.setText("Please specify names of elements for reactants");

        jTextFieldReactant1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldReactant1.setText("Enter Name Here");

        jTextFieldReactant2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldReactant2.setText("Enter Name Here");

        jButtonTryAnother.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonTryAnother.setText("Try Another");
        jButtonTryAnother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTryAnotherActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelEquationPlus.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelEquationPlus.setText("+");

        jLabelEquationArrow.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelEquationArrow.setText("→");

        jLabelEquationProductA.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelEquationProductA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationProductA.setText("A");

        jLabelProductName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductName.setText("Name:");

        jLabelProductMolarMass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductMolarMass.setText("Molar Mass:");

        jLabelProductStpState.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductStpState.setText("State @ STP:");

        jLabelProductStpDensity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductStpDensity.setText("Density @ STP:");

        jLabelProductMP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductMP.setText("Melting Point:");

        jLabelProductBP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductBP.setText("Boiling Point:");

        jLabelProductColour.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProductColour.setText("Colour: ");

        jLabelProductCharge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProductCharge.setText("[Charge]");

        jTextFieldProductName.setText("Enter Name Here");

        jLabelEquationReactant2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelEquationReactant2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationReactant2.setText("B");

        jLabelEquationReactant1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelEquationReactant1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationReactant1.setText("A");

        jLabelEquationProductB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelEquationProductB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationProductB.setText("B");

        jLabelEquationProductSubscriptA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEquationProductSubscriptA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationProductSubscriptA.setText("a");

        jLabelEquationProductSubscriptB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEquationProductSubscriptB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquationProductSubscriptB.setText("b");

        jLabelMolecularFormulaReactant1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMolecularFormulaReactant1.setText("A");

        jLabelProtonsReactant1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProtonsReactant1.setText("[Protons]");

        jLabelMassReactant1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMassReactant1.setText("[Mass Number]");

        jLabelProductSubscriptB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelProductSubscriptB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductSubscriptB.setText("b");

        jLabelProductA.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelProductA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductA.setText("A");

        jLabelProductB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelProductB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductB.setText("B");

        jLabelProductSubscriptA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelProductSubscriptA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductSubscriptA.setText("a");

        jLabelOxNumReactant1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelOxNumReactant1.setText("[Oxidation #]");

        jLabelMolecularFormulaReactant2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMolecularFormulaReactant2.setText("B");

        jLabelProtonsReactant2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProtonsReactant2.setText("[Protons]");

        jLabelMassReactant2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMassReactant2.setText("[Mass Number]");

        jLabelOxNumReactant2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelOxNumReactant2.setText("[Oxidation #]");

        jButtonSubmitProductName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSubmitProductName.setText("SUBMIT");
        jButtonSubmitProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitProductNameActionPerformed(evt);
            }
        });

        jLabelEquationProductCharge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEquationProductCharge.setText("[Charge]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonSubmitReactants)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTryAnother))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTitle)
                        .addGap(200, 200, 200)
                        .addComponent(jButtonBack)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabelReactant1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jTextFieldReactant1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelProtonsReactant1)
                            .addComponent(jLabelMassReactant1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMolecularFormulaReactant1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelOxNumReactant1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldReactant2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelProtonsReactant2)
                            .addComponent(jLabelMassReactant2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMolecularFormulaReactant2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelOxNumReactant2)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelReactant2)
                        .addGap(179, 179, 179))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabelEquationArrow))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEquationReactant1)
                        .addGap(49, 49, 49)
                        .addComponent(jLabelEquationPlus)
                        .addGap(68, 68, 68)
                        .addComponent(jLabelEquationReactant2)))
                .addGap(48, 48, 48)
                .addComponent(jLabelEquationProductA)
                .addGap(4, 4, 4)
                .addComponent(jLabelEquationProductSubscriptA)
                .addGap(3, 3, 3)
                .addComponent(jLabelEquationProductB)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEquationProductSubscriptB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelEquationProductCharge)))
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelEquation))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabelProduct)
                                .addGap(123, 123, 123))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelProductA)
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelProductSubscriptA)
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabelProductB)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelProductSubscriptB)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelProductCharge))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelProductName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jButtonSubmitProductName))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelProductBP)
                                    .addComponent(jLabelProductMP)
                                    .addComponent(jLabelProductColour)
                                    .addComponent(jLabelProductStpState)
                                    .addComponent(jLabelProductMolarMass)
                                    .addComponent(jLabelProductStpDensity))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jButtonBack))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelReactant1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldReactant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelReactant2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldReactant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelMolecularFormulaReactant1)
                                .addComponent(jLabelMassReactant1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelOxNumReactant1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabelProtonsReactant1))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSubmitReactants)
                            .addComponent(jLabelInfo)
                            .addComponent(jButtonTryAnother)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMolecularFormulaReactant2)
                            .addComponent(jLabelMassReactant2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOxNumReactant2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(jLabelProtonsReactant2)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelProductA)
                                    .addComponent(jLabelProductB))
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelProductSubscriptB)
                                    .addComponent(jLabelProductSubscriptA))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProductName)
                            .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSubmitProductName))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProductMolarMass)
                            .addComponent(jLabelProductCharge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelProductStpDensity)
                        .addGap(4, 4, 4)
                        .addComponent(jLabelProductStpState)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelProductMP)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelProductBP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelProductColour)))
                .addGap(22, 22, 22)
                .addComponent(jLabelEquation)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEquationPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEquationArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEquationProductA)
                                    .addComponent(jLabelEquationReactant2)
                                    .addComponent(jLabelEquationReactant1)
                                    .addComponent(jLabelEquationProductB))
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelEquationProductSubscriptB)
                                    .addComponent(jLabelEquationProductSubscriptA))))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEquationProductCharge)
                        .addGap(69, 69, 69))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        if(nameEntered || noProduct){
            Home.start();
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Please name your product!");
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSubmitReactantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitReactantsActionPerformed
        this.jButtonTryAnother.setEnabled(true);
        this.jButtonSubmitReactants.setEnabled(false);
        this.jTextFieldReactant1.setEnabled(false);
        this.jTextFieldReactant2.setEnabled(false);
        
        Chemical tempChemical1 = DatabaseGUI.getDatabase().searchChemicalsByName(this.jTextFieldReactant1.getText());
        Chemical tempChemical2 = DatabaseGUI.getDatabase().searchChemicalsByName(this.jTextFieldReactant2.getText());
        
        if (tempChemical1 instanceof Element && tempChemical2 instanceof Element) {
            reactant1 = (Element)tempChemical1;
            reactant2 = (Element)tempChemical2;
            
            if (reactant1 == reactant2) sameReactants = true;
            
            //Reactant 1
            this.jLabelMassReactant1.setText("" + (reactant1.getNumProton() + reactant1.getNumNeutron()));
            this.jLabelProtonsReactant1.setText("" + reactant1.getNumProton());
            this.jLabelMolecularFormulaReactant1.setText(reactant1.getMolecularFormula());
            this.jLabelOxNumReactant1.setText("" + reactant1.getOxidationNum());
            
            //Reactant 2
            this.jLabelMassReactant2.setText("" + (reactant2.getNumProton() + reactant1.getNumNeutron()));
            this.jLabelProtonsReactant2.setText("" + reactant2.getNumProton());
            this.jLabelMolecularFormulaReactant2.setText(reactant2.getMolecularFormula());
            this.jLabelOxNumReactant2.setText("" + reactant2.getOxidationNum());
            
            id = DatabaseGUI.getDatabase().getReactionManager().getReactionList().size();
            
            reaction = DatabaseGUI.simulateReaction(id, reactant1, reactant2);
  
            if (reaction != null) {
                JOptionPane.showMessageDialog(null, "New reaction successful!");
                
                this.jButtonSubmitProductName.setEnabled(true);
                this.jTextFieldProductName.setEnabled(true);
                noProduct = false;

                product = reaction.getProduct();
                
                //Check if Reactants are the same
                if (!sameReactants) {
                    //Product Formulas
                    this.jLabelProductA.setText(product.getComponent1().getComponent().getMolecularFormula());
                    this.jLabelProductB.setText(product.getComponent2().getComponent().getMolecularFormula());
                    this.jLabelEquationProductA.setText(product.getComponent1().getComponent().getMolecularFormula());
                    this.jLabelEquationProductB.setText(product.getComponent2().getComponent().getMolecularFormula());

                    //Subscripts
                    if (product.getComponent1().getNumOccurrence() > 1) {
                        this.jLabelProductSubscriptA.setText("" + product.getComponent1().getNumOccurrence());
                        this.jLabelEquationProductSubscriptA.setText("" + product.getComponent1().getNumOccurrence());
                    } else {
                        this.jLabelProductSubscriptA.setText("");
                        this.jLabelEquationProductSubscriptA.setText("");
                    }
                    if (product.getComponent2().getNumOccurrence() > 1) {
                        this.jLabelProductSubscriptB.setText("" + product.getComponent2().getNumOccurrence());
                        this.jLabelEquationProductSubscriptB.setText("" + product.getComponent2().getNumOccurrence());
                    } else {
                        this.jLabelProductSubscriptB.setText("");
                        this.jLabelEquationProductSubscriptB.setText("");
                    }
                } else {
                    this.jLabelProductA.setText("");
                    this.jLabelProductSubscriptA.setText("");
                    this.jLabelEquationProductA.setText("");
                    this.jLabelEquationProductSubscriptA.setText("");
                    
                    this.jLabelProductB.setText(product.getComponent2().getComponent().getMolecularFormula());
                    this.jLabelProductSubscriptB.setText("" + (product.getComponent1().getNumOccurrence() + product.getComponent2().getNumOccurrence()));
                    this.jLabelEquationProductB.setText(product.getComponent2().getComponent().getMolecularFormula());
                    this.jLabelEquationProductSubscriptB.setText("" + (product.getComponent1().getNumOccurrence() + product.getComponent2().getNumOccurrence()));
                }
                
                //Reactants in Equation
                this.jLabelEquationReactant1.setText(reactant1.getMolecularFormula());
                this.jLabelEquationReactant2.setText(reactant2.getMolecularFormula());
                
                //Product Properties
                this.jLabelProductMolarMass.setText("Molar Mass: " + product.getMolarMass());
                this.jLabelProductStpDensity.setText("Density @ STP: " + product.getStpDensity());
                this.jLabelProductStpState.setText("State @ STP: " + product.getStpState());
                this.jLabelProductMP.setText("Melting Point: " + product.getMP());
                this.jLabelProductBP.setText("Boiling Point: " + product.getBP());
                this.jLabelProductColour.setText("Colour: " + product.getColour());
                
                //Set Charges for both
                int charge = product.getCharge();
                if (charge != 0) {
                    if (charge > 0) {
                        this.jLabelProductCharge.setText("+" + charge);
                        this.jLabelEquationProductCharge.setText("+" + charge);
                    } else {
                        this.jLabelProductCharge.setText("" + charge);
                        this.jLabelEquationProductCharge.setText("" + charge);
                    }
                } else {
                    this.jLabelProductCharge.setText("");
                    this.jLabelEquationProductCharge.setText("");
                }
            } else {
                if (reactant1.getOxidationNum() == 0 || reactant2.getOxidationNum() == 0) 
                    JOptionPane.showMessageDialog(null, "Reaction not possible!");
                else 
                    JOptionPane.showMessageDialog(null, "Reaction already exists!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Reactant not found!");
        }
    }//GEN-LAST:event_jButtonSubmitReactantsActionPerformed

    private void jButtonTryAnotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTryAnotherActionPerformed
        if(nameEntered || noProduct){
            noProduct = true;
            nameEntered = false;

            this.jButtonTryAnother.setEnabled(false);
            this.jButtonSubmitReactants.setEnabled(true);
            this.jButtonSubmitProductName.setEnabled(false);
            this.jTextFieldProductName.setEnabled(false);
            this.jTextFieldReactant1.setEnabled(true);
            this.jTextFieldReactant2.setEnabled(true);

            sameReactants = false;

            this.jTextFieldReactant1.setText("Enter Name Here");
            this.jLabelMassReactant1.setText("[Mass Number]");
            this.jLabelProtonsReactant1.setText("[Protons]");
            this.jLabelOxNumReactant1.setText("[Oxidation #]");
            this.jLabelMolecularFormulaReactant1.setText("A");

            this.jTextFieldReactant2.setText("Enter Name Here");
            this.jLabelMassReactant2.setText("[Mass Number]");
            this.jLabelProtonsReactant2.setText("[Protons]");
            this.jLabelOxNumReactant2.setText("[Oxidation #]");
            this.jLabelMolecularFormulaReactant2.setText("B");

            this.jTextFieldProductName.setText("Enter Name Here");
            this.jLabelProductMolarMass.setText("Molar Mass: ");
            this.jLabelProductStpDensity.setText("Density @ STP: ");
            this.jLabelProductStpState.setText("State @ STP: ");
            this.jLabelProductMP.setText("Melting Point: ");
            this.jLabelProductBP.setText("Boiling Point: ");
            this.jLabelProductColour.setText("Colour: ");
            this.jLabelProductA.setText("A");
            this.jLabelProductSubscriptA.setText("a");
            this.jLabelProductB.setText("B");
            this.jLabelProductSubscriptB.setText("b");
            this.jLabelProductCharge.setText("[Charge]");

            this.jLabelEquationReactant1.setText("A");
            this.jLabelEquationReactant2.setText("B");
            this.jLabelEquationProductA.setText("A");
            this.jLabelEquationProductB.setText("B");
            this.jLabelEquationProductSubscriptA.setText("a");
            this.jLabelEquationProductSubscriptB.setText("b");
            this.jLabelEquationProductCharge.setText("[Charge]");
        }else
            JOptionPane.showMessageDialog(null, "Please name your product!");
    }//GEN-LAST:event_jButtonTryAnotherActionPerformed

    private void jButtonSubmitProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitProductNameActionPerformed
        String name = this.jTextFieldProductName.getText();
        
        //check repeats for name
        if(name.equals(Chemical.getDEFAULT_COMMON_NAME()) || name.equals(""))
            JOptionPane.showMessageDialog(null, "Illegal name!");
        else if(DatabaseGUI.getDatabase().commonNameRepeats(name))
            JOptionPane.showMessageDialog(null, name + " already exists!");
        else{
            product.setCommonName(name);
            nameEntered = true;
            JOptionPane.showMessageDialog(null, "Name set successfully!");
        }
    }//GEN-LAST:event_jButtonSubmitProductNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulateReaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulateReaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulateReaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulateReaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulateReaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSubmitProductName;
    private javax.swing.JButton jButtonSubmitReactants;
    private javax.swing.JButton jButtonTryAnother;
    private javax.swing.JLabel jLabelEquation;
    private javax.swing.JLabel jLabelEquationArrow;
    private javax.swing.JLabel jLabelEquationPlus;
    private javax.swing.JLabel jLabelEquationProductA;
    private javax.swing.JLabel jLabelEquationProductB;
    private javax.swing.JLabel jLabelEquationProductCharge;
    private javax.swing.JLabel jLabelEquationProductSubscriptA;
    private javax.swing.JLabel jLabelEquationProductSubscriptB;
    private javax.swing.JLabel jLabelEquationReactant1;
    private javax.swing.JLabel jLabelEquationReactant2;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelMassReactant1;
    private javax.swing.JLabel jLabelMassReactant2;
    private javax.swing.JLabel jLabelMolecularFormulaReactant1;
    private javax.swing.JLabel jLabelMolecularFormulaReactant2;
    private javax.swing.JLabel jLabelOxNumReactant1;
    private javax.swing.JLabel jLabelOxNumReactant2;
    private javax.swing.JLabel jLabelProduct;
    private javax.swing.JLabel jLabelProductA;
    private javax.swing.JLabel jLabelProductB;
    private javax.swing.JLabel jLabelProductBP;
    private javax.swing.JLabel jLabelProductCharge;
    private javax.swing.JLabel jLabelProductColour;
    private javax.swing.JLabel jLabelProductMP;
    private javax.swing.JLabel jLabelProductMolarMass;
    private javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelProductStpDensity;
    private javax.swing.JLabel jLabelProductStpState;
    private javax.swing.JLabel jLabelProductSubscriptA;
    private javax.swing.JLabel jLabelProductSubscriptB;
    private javax.swing.JLabel jLabelProtonsReactant1;
    private javax.swing.JLabel jLabelProtonsReactant2;
    private javax.swing.JLabel jLabelReactant1;
    private javax.swing.JLabel jLabelReactant2;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldProductName;
    private javax.swing.JTextField jTextFieldReactant1;
    private javax.swing.JTextField jTextFieldReactant2;
    // End of variables declaration//GEN-END:variables
}
