package gui;

import databaserunner.DatabaseGUI;
import javax.swing.*;

public class AddElement extends javax.swing.JFrame {

    //our fields
    private static String name;
    private static String molecularFormula;
    private static int numProton;
    private static int numNeutron;
    private static char stpState;
    private static double stpDensity;
    private static double molarMass;
    private static double bp;
    private static double mp;
    private static String colour;
    private static double ionizationEnergy;
    private static double electronegativity;
    
    /**
     * Creates new form AddElement
     */
    public AddElement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAddElement = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelStpState = new javax.swing.JLabel();
        jLabelStpDensity = new javax.swing.JLabel();
        jLabelMolarMass = new javax.swing.JLabel();
        jLabelBP = new javax.swing.JLabel();
        jLabelMP = new javax.swing.JLabel();
        jLabelColour = new javax.swing.JLabel();
        jLabelNumProton = new javax.swing.JLabel();
        jLabelNumNeutron = new javax.swing.JLabel();
        jLabelIonizationEnergy = new javax.swing.JLabel();
        jLabelElectronegativity = new javax.swing.JLabel();
        jLabelMolecularFormula = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldMolecularFormula = new javax.swing.JTextField();
        jTextFieldNumProton = new javax.swing.JTextField();
        jTextFieldNumNeutron = new javax.swing.JTextField();
        jTextFieldStpState = new javax.swing.JTextField();
        jTextFieldStpDensity = new javax.swing.JTextField();
        jTextFieldMolarMass = new javax.swing.JTextField();
        jTextFieldBP = new javax.swing.JTextField();
        jTextFieldMP = new javax.swing.JTextField();
        jTextFieldColour = new javax.swing.JTextField();
        jTextFieldIonizationEnergy = new javax.swing.JTextField();
        jTextFieldElectronegativity = new javax.swing.JTextField();
        jLabelInfo = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAddElement.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelAddElement.setText("Add Element");

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelName.setText("*Name:");

        jLabelStpState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelStpState.setText("State @ STP:");

        jLabelStpDensity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelStpDensity.setText("Density @ STP (g/L):");

        jLabelMolarMass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMolarMass.setText("Molar Mass (g/mol):");

        jLabelBP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBP.setText("Boiling Point (C):");

        jLabelMP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMP.setText("Melting Point (C):");

        jLabelColour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelColour.setText("Colour:");

        jLabelNumProton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumProton.setText("*Protons:");

        jLabelNumNeutron.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumNeutron.setText("Neutrons:");

        jLabelIonizationEnergy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIonizationEnergy.setText("Ionization Energy:");

        jLabelElectronegativity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelElectronegativity.setText("Electronegativity:");

        jLabelMolecularFormula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMolecularFormula.setText("*Molecular Formula:");

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldMolecularFormula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldNumProton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldNumNeutron.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldStpState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldStpDensity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldMolarMass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldBP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldMP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldColour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldIonizationEnergy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldElectronegativity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInfo.setText("* = required fields");

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelElectronegativity)
                    .addComponent(jLabelMolecularFormula)
                    .addComponent(jLabelName)
                    .addComponent(jLabelIonizationEnergy)
                    .addComponent(jLabelColour)
                    .addComponent(jLabelMP)
                    .addComponent(jLabelBP)
                    .addComponent(jLabelMolarMass)
                    .addComponent(jLabelStpDensity)
                    .addComponent(jLabelStpState)
                    .addComponent(jLabelNumNeutron)
                    .addComponent(jLabelNumProton)
                    .addComponent(jLabelAddElement))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInfo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldElectronegativity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jTextFieldIonizationEnergy, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldColour, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldMP, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldBP, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldMolarMass, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldStpDensity, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldStpState, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldNumNeutron, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldNumProton, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldMolecularFormula, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(67, 67, 67)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddElement)
                    .addComponent(jLabelInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMolecularFormula)
                    .addComponent(jTextFieldMolecularFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumProton)
                    .addComponent(jTextFieldNumProton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumNeutron)
                    .addComponent(jTextFieldNumNeutron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStpState)
                    .addComponent(jTextFieldStpState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStpDensity)
                    .addComponent(jTextFieldStpDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMolarMass)
                    .addComponent(jTextFieldMolarMass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBP)
                    .addComponent(jTextFieldBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMP)
                    .addComponent(jTextFieldMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelColour)
                    .addComponent(jTextFieldColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIonizationEnergy)
                    .addComponent(jTextFieldIonizationEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelElectronegativity)
                    .addComponent(jTextFieldElectronegativity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSubmit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //SUBMIT button
    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        try{
            //read all values
            name = jTextFieldName.getText();
            molecularFormula = jTextFieldMolecularFormula.getText();
            numProton = Integer.parseInt(jTextFieldNumProton.getText());
            numNeutron = Integer.parseInt(jTextFieldNumNeutron.getText());
            stpState = jTextFieldStpState.getText().charAt(0);
            stpDensity = Double.parseDouble(jTextFieldStpDensity.getText());
            molarMass = Double.parseDouble(jTextFieldMolarMass.getText());
            bp = Double.parseDouble(jTextFieldBP.getText());
            mp = Double.parseDouble(jTextFieldMP.getText());
            colour = jTextFieldColour.getText();
            ionizationEnergy = Double.parseDouble(jTextFieldIonizationEnergy.getText());
            electronegativity = Double.parseDouble(jTextFieldElectronegativity.getText());
        }catch(NumberFormatException nfx){
            JOptionPane.showMessageDialog(null, "Erroneous data has been entered!");
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    //Back button
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        Home.start();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddElement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabelAddElement;
    private javax.swing.JLabel jLabelBP;
    private javax.swing.JLabel jLabelColour;
    private javax.swing.JLabel jLabelElectronegativity;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelIonizationEnergy;
    private javax.swing.JLabel jLabelMP;
    private javax.swing.JLabel jLabelMolarMass;
    private javax.swing.JLabel jLabelMolecularFormula;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNumNeutron;
    private javax.swing.JLabel jLabelNumProton;
    private javax.swing.JLabel jLabelStpDensity;
    private javax.swing.JLabel jLabelStpState;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBP;
    private javax.swing.JTextField jTextFieldColour;
    private javax.swing.JTextField jTextFieldElectronegativity;
    private javax.swing.JTextField jTextFieldIonizationEnergy;
    private javax.swing.JTextField jTextFieldMP;
    private javax.swing.JTextField jTextFieldMolarMass;
    private javax.swing.JTextField jTextFieldMolecularFormula;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNumNeutron;
    private javax.swing.JTextField jTextFieldNumProton;
    private javax.swing.JTextField jTextFieldStpDensity;
    private javax.swing.JTextField jTextFieldStpState;
    // End of variables declaration//GEN-END:variables
}
