package gui;

import javax.swing.*;
import databaserunner.DatabaseGUI;

public class Start extends javax.swing.JFrame {

    //our fields
    private static String elementsFile;
    private static String binaryCompoundsFile;
    private static String reactionsFile;
    private static int firstValence;
    private static int increment;
    
    //our accessors & mutators
    public static String getElementsFile(){
        return elementsFile;
    }
    public static void setElementsFile(String newElementsFile){
        elementsFile = newElementsFile;
    }
    
    public static String getBinaryCompoundsFile(){
        return binaryCompoundsFile;
    }
    public static void setBinaryCompoundsFile(String newBinaryCompoundsFile){
        binaryCompoundsFile = newBinaryCompoundsFile;
    }
    
    public static String getReactionsFile(){
        return reactionsFile;
    }
    public static void setReactionsFile(String newReactionsFile){
        reactionsFile = newReactionsFile;
    }
    
    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel("TITLE", SwingConstants.CENTER);
        jTextFieldElementsFileName = new javax.swing.JTextField();
        jComboBoxFirstValence = new javax.swing.JComboBox<>();
        jComboBoxIncrement = new javax.swing.JComboBox<>();
        jLabelIncrement = new javax.swing.JLabel();
        jLabelFirstValence = new javax.swing.JLabel();
        jLabelElementsFileName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelBinaryCompoundsFileName = new javax.swing.JLabel();
        jTextFieldBinaryCompoundsFileName = new javax.swing.JTextField();
        jLabelReactionsFileName = new javax.swing.JLabel();
        jTextFieldReactionsFileName = new javax.swing.JTextField();
        jLabelInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitle.setText("Welcome to The Chemical Database!");

        jTextFieldElementsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldElementsFileName.setText("elements.txt");

        jComboBoxFirstValence.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxFirstValence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBoxFirstValence.setSelectedItem("2");

        jComboBoxIncrement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxIncrement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBoxIncrement.setSelectedItem("4");

        jLabelIncrement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIncrement.setText("Increment");

        jLabelFirstValence.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFirstValence.setText("First Valence");

        jLabelElementsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelElementsFileName.setText("*Elements File Name");

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("INSTRUCTIONS");
        jScrollPane1.setViewportView(jTextArea1);

        jLabelBinaryCompoundsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBinaryCompoundsFileName.setText("Compounds File Name");

        jTextFieldBinaryCompoundsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldBinaryCompoundsFileName.setText("glate.txt");

        jLabelReactionsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelReactionsFileName.setText("Reactions File Name");

        jTextFieldReactionsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldReactionsFileName.setText("glate.txt");

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInfo.setText("* = required field");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelElementsFileName)
                            .addComponent(jTextFieldElementsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFirstValence)
                            .addComponent(jComboBoxFirstValence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxIncrement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIncrement))
                        .addGap(179, 179, 179))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelInfo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldReactionsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelReactionsFileName)
                            .addComponent(jTextFieldBinaryCompoundsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBinaryCompoundsFileName))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelElementsFileName)
                    .addComponent(jLabelFirstValence)
                    .addComponent(jLabelIncrement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldElementsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFirstValence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxIncrement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBinaryCompoundsFileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBinaryCompoundsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelReactionsFileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldReactionsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubmit)
                    .addComponent(jLabelInfo))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //SUBMIT button
    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        elementsFile = jTextFieldElementsFileName.getText();
        binaryCompoundsFile = jTextFieldBinaryCompoundsFileName.getText();
        reactionsFile = jTextFieldReactionsFileName.getText();
        firstValence = Integer.parseInt((String)(jComboBoxFirstValence.getSelectedItem()));
        increment = Integer.parseInt((String)(jComboBoxIncrement.getSelectedItem()));
        
        if(DatabaseGUI.constructDatabase(elementsFile, binaryCompoundsFile, reactionsFile, firstValence, increment))        
            this.setVisible(false);
        else
            JOptionPane.showMessageDialog(null, "Elements file does not exist!");
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboBoxFirstValence;
    private javax.swing.JComboBox<String> jComboBoxIncrement;
    private javax.swing.JLabel jLabelBinaryCompoundsFileName;
    private javax.swing.JLabel jLabelElementsFileName;
    private javax.swing.JLabel jLabelFirstValence;
    private javax.swing.JLabel jLabelIncrement;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelReactionsFileName;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldBinaryCompoundsFileName;
    private javax.swing.JTextField jTextFieldElementsFileName;
    private javax.swing.JTextField jTextFieldReactionsFileName;
    // End of variables declaration//GEN-END:variables
}
