package gui;

import databaserunner.*;
import javax.swing.*;

public class AddElement extends javax.swing.JFrame {

    //our fields
    private DatabaseGUI databaseGUI;
    
    /**
     * Creates new form AddElement
     */
    public AddElement(DatabaseGUI databaseGUI) {
        this.databaseGUI = databaseGUI;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeTitle = new javax.swing.JLabel();
        jLabelCommonName = new javax.swing.JLabel();
        jLabelStpDensity = new javax.swing.JLabel();
        jLabelMolarMass = new javax.swing.JLabel();
        jLabelBP = new javax.swing.JLabel();
        jLabelMP = new javax.swing.JLabel();
        jLabelColour = new javax.swing.JLabel();
        jLabelNumProton = new javax.swing.JLabel();
        jLabelNumNeutron = new javax.swing.JLabel();
        jLabelIonizationEnergy = new javax.swing.JLabel();
        jLabelElectronegativity = new javax.swing.JLabel();
        jLabelMolecularFormula = new javax.swing.JLabel();
        jTextFieldCommonName = new javax.swing.JTextField();
        jTextFieldMolecularFormula = new javax.swing.JTextField();
        jTextFieldNumProton = new javax.swing.JTextField();
        jTextFieldNumNeutron = new javax.swing.JTextField();
        jTextFieldStpDensity = new javax.swing.JTextField();
        jTextFieldMolarMass = new javax.swing.JTextField();
        jTextFieldBP = new javax.swing.JTextField();
        jTextFieldMP = new javax.swing.JTextField();
        jTextFieldColour = new javax.swing.JTextField();
        jTextFieldIonizationEnergy = new javax.swing.JTextField();
        jTextFieldElectronegativity = new javax.swing.JTextField();
        jLabelInfo = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabeTitle.setText("Add Element");

        jLabelCommonName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCommonName.setText("*Name:");

        jLabelStpDensity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelStpDensity.setText("Density @ STP (g/L):");

        jLabelMolarMass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMolarMass.setText("Molar Mass (g/mol):");

        jLabelBP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBP.setText("Boiling Point (C):");

        jLabelMP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMP.setText("Melting Point (C):");

        jLabelColour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelColour.setText("Colour:");

        jLabelNumProton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumProton.setText("*Protons (Atomic #):");

        jLabelNumNeutron.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumNeutron.setText("Neutrons:");

        jLabelIonizationEnergy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIonizationEnergy.setText("Ionization Energy:");

        jLabelElectronegativity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelElectronegativity.setText("*Electronegativity:");

        jLabelMolecularFormula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMolecularFormula.setText("*Atomic Symbol:");

        jTextFieldCommonName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldMolecularFormula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldNumProton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldNumNeutron.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldStpDensity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldMolarMass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldBP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldMP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldColour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldIonizationEnergy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldElectronegativity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInfo.setText("* = required fields");

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabeTitle)
                        .addGap(67, 67, 67)
                        .addComponent(jLabelInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMolecularFormula)
                            .addComponent(jLabelCommonName))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldMolecularFormula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCommonName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIonizationEnergy)
                            .addComponent(jLabelColour)
                            .addComponent(jLabelMP)
                            .addComponent(jLabelBP)
                            .addComponent(jLabelMolarMass)
                            .addComponent(jLabelStpDensity)
                            .addComponent(jLabelNumNeutron))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldIonizationEnergy, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldColour, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMolarMass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldStpDensity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumNeutron, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumProton)
                            .addComponent(jLabelElectronegativity))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldElectronegativity, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextFieldNumProton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                        .addComponent(jButtonSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeTitle)
                            .addComponent(jLabelInfo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCommonName)
                            .addComponent(jTextFieldCommonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMolecularFormula)
                            .addComponent(jTextFieldMolecularFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumProton)
                            .addComponent(jTextFieldNumProton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelElectronegativity)
                            .addComponent(jTextFieldElectronegativity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumNeutron)
                            .addComponent(jTextFieldNumNeutron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStpDensity)
                            .addComponent(jTextFieldStpDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMolarMass)
                            .addComponent(jTextFieldMolarMass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBP)
                            .addComponent(jTextFieldBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMP)
                            .addComponent(jTextFieldMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelColour)
                            .addComponent(jTextFieldColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIonizationEnergy)
                            .addComponent(jTextFieldIonizationEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //SUBMIT button
    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        //declare variables
        String commonName;
        String molecularFormula;
        int numProton;
        int numNeutron;
        double stpDensity;
        double molarMass;
        double bp;
        double mp;
        String colour;
        double ionizationEnergy;
        double electronegativity;
        
        try{
            //read required fields
            commonName = this.jTextFieldCommonName.getText();
            molecularFormula = this.jTextFieldMolecularFormula.getText();
            numProton = Integer.parseInt(this.jTextFieldNumProton.getText());
            electronegativity = Double.parseDouble(this.jTextFieldElectronegativity.getText());
            
            //read optional fields
            if(!this.jTextFieldNumNeutron.getText().equals(DatabaseGUI.EMPTY_STRING)){
                numNeutron = Integer.parseInt(this.jTextFieldNumNeutron.getText());
            }else
                numNeutron = NuclearProperties.getDEFAULT_NEUTRONS();
            
            if(!this.jTextFieldStpDensity.getText().equals(DatabaseGUI.EMPTY_STRING)){
                stpDensity = Double.parseDouble(this.jTextFieldStpDensity.getText());
            }else
                stpDensity = Chemical.getDEFAULT_DENSITY();
            
            if(!this.jTextFieldMolarMass.getText().equals(DatabaseGUI.EMPTY_STRING)){
                molarMass = Double.parseDouble(this.jTextFieldMolarMass.getText());
            }else
                molarMass = Chemical.getDEFAULT_MOLAR_MASS();
            
            if(!this.jTextFieldBP.getText().equals(DatabaseGUI.EMPTY_STRING)){
                bp = Double.parseDouble(this.jTextFieldBP.getText());
            }else
                bp = Chemical.getDEFAULT_STATE_CHANGE_TEMP();
            
            if(!this.jTextFieldMP.getText().equals(DatabaseGUI.EMPTY_STRING)){
                mp = Double.parseDouble(this.jTextFieldMP.getText());
            }else
                mp = Chemical.getDEFAULT_STATE_CHANGE_TEMP();
            
            if(!this.jTextFieldColour.getText().equals(DatabaseGUI.EMPTY_STRING))
                colour = this.jTextFieldColour.getText();
            else
                colour = Chemical.getDEFAULT_COLOUR();
            
            if(!this.jTextFieldIonizationEnergy.getText().equals(DatabaseGUI.EMPTY_STRING)){
                ionizationEnergy = Double.parseDouble(this.jTextFieldIonizationEnergy.getText());
            }else
                ionizationEnergy = NuclearProperties.getDEFAULT_IONIZATION_ENERGY();
            
            //create new Element and add it to the database only if properties pass all checks
            Element newElement = new Element(commonName, stpDensity, molarMass, bp, mp, colour, numProton, numNeutron, ionizationEnergy, electronegativity, molecularFormula);
            
            if(this.jTextFieldCommonName.getText().equals(DatabaseGUI.EMPTY_STRING) || this.jTextFieldMolecularFormula.getText().equals(DatabaseGUI.EMPTY_STRING) || this.jTextFieldNumProton.getText().equals(DatabaseGUI.EMPTY_STRING) || this.jTextFieldElectronegativity.getText().equals(DatabaseGUI.EMPTY_STRING))
                JOptionPane.showMessageDialog(null, "A required field is blank!");
            
            else if(commonName.equals(Chemical.getDEFAULT_COMMON_NAME()))
                JOptionPane.showMessageDialog(null, "Illegal name!");
            
            else if(molecularFormula.equals(Chemical.getDEFAULT_MOLECULAR_FORMULA()))
                JOptionPane.showMessageDialog(null, "Illegal molecular formula!");
            
            else if(numProton <= NuclearProperties.getDEFAULT_PROTONS())
                JOptionPane.showMessageDialog(null, "Illegal atomic number!");
            
            else if(electronegativity <= NuclearProperties.MIN_ELECTRONEGATIVITY() || electronegativity > NuclearProperties.MAX_ELECTRONEGATIVITY())
                JOptionPane.showMessageDialog(null, "Illegal electronegativity!");
            
            else if(numNeutron < NuclearProperties.getDEFAULT_NEUTRONS())
                JOptionPane.showMessageDialog(null, "Illegal neutron quantity!");
            
            else if(stpDensity < Chemical.getDEFAULT_DENSITY())
                JOptionPane.showMessageDialog(null, "Illegal density!");
            
            else if(molarMass < Chemical.getDEFAULT_MOLAR_MASS())
                JOptionPane.showMessageDialog(null, "Illegal molar mass!");
            
            else if(bp < Chemical.getDEFAULT_STATE_CHANGE_TEMP())
                JOptionPane.showMessageDialog(null, "Illegal boiling point!");
            
            else if(mp < Chemical.getDEFAULT_STATE_CHANGE_TEMP())
                JOptionPane.showMessageDialog(null, "Illegal melting point!");
            
            else if(ionizationEnergy < NuclearProperties.getDEFAULT_IONIZATION_ENERGY())
                JOptionPane.showMessageDialog(null, "Illegal ionization energy!");
            
            else if(this.databaseGUI.addElement(newElement)){
                this.databaseGUI.startHomePage();
                this.setVisible(false);
                
            }else
                JOptionPane.showMessageDialog(null, "An element with that information already exists!");
            
        }catch(NumberFormatException nfx){
            JOptionPane.showMessageDialog(null, "Erroneous data has been entered!");
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    //Back button
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.databaseGUI.startHomePage();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddElement(databaseGUI).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabeTitle;
    private javax.swing.JLabel jLabelBP;
    private javax.swing.JLabel jLabelColour;
    private javax.swing.JLabel jLabelCommonName;
    private javax.swing.JLabel jLabelElectronegativity;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelIonizationEnergy;
    private javax.swing.JLabel jLabelMP;
    private javax.swing.JLabel jLabelMolarMass;
    private javax.swing.JLabel jLabelMolecularFormula;
    private javax.swing.JLabel jLabelNumNeutron;
    private javax.swing.JLabel jLabelNumProton;
    private javax.swing.JLabel jLabelStpDensity;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBP;
    private javax.swing.JTextField jTextFieldColour;
    private javax.swing.JTextField jTextFieldCommonName;
    private javax.swing.JTextField jTextFieldElectronegativity;
    private javax.swing.JTextField jTextFieldIonizationEnergy;
    private javax.swing.JTextField jTextFieldMP;
    private javax.swing.JTextField jTextFieldMolarMass;
    private javax.swing.JTextField jTextFieldMolecularFormula;
    private javax.swing.JTextField jTextFieldNumNeutron;
    private javax.swing.JTextField jTextFieldNumProton;
    private javax.swing.JTextField jTextFieldStpDensity;
    // End of variables declaration//GEN-END:variables
}
