package gui;

import java.util.*;
import databaserunner.*;
import javax.swing.*;

public class ListReactions extends javax.swing.JFrame {

    //our fields
    private static final String[] HEADER = {"Reactant 1", "Reactant 2", "Product"};
    private static final int NUM_COL = 3;
    
    private List<Reaction> reactions;
    private String[][] table = {};
    
    private DatabaseGUI databaseGUI;

    /**
     * Creates new form ListReactions
     */
    public ListReactions(DatabaseGUI databaseGUI) {
        this.databaseGUI = databaseGUI;
        this.initComponents();
    }
    
    public void start(ListReactions listReactions) {
        this.createTable();
        this.jTableReactions.setDefaultEditor(Object.class, null);
        
        this.jTableReactions.setModel(new javax.swing.table.DefaultTableModel(
            table,
            HEADER
        ));
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                listReactions.setVisible(true);
            }
        });
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.removeWindowListener(this.databaseGUI.WINDOW_CLOSE);
        
        if (DatabaseGUI.getMadeChanges()) {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            this.addWindowListener(this.databaseGUI.WINDOW_CLOSE);
        }
    }

    private void createTable(){
        this.reactions = this.databaseGUI.listReactions();

        this.table = new String[this.reactions.size()][NUM_COL];
        for(int i = 0; i < this.reactions.size(); i++){
            this.table[i][0] = this.reactions.get(i).getReactant1().getAtomicSymbol();
            this.table[i][1] = this.reactions.get(i).getReactant2().getAtomicSymbol();
            this.table[i][2] = this.reactions.get(i).getProduct().getMolecularFormula();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReactions = new javax.swing.JTable();
        jButtonRemoveReaction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitle.setText("List Reactions");

        jTableReactions.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableReactions.setModel(new javax.swing.table.DefaultTableModel(
            table,
            HEADER
        ));
        jTableReactions.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableReactions);

        jButtonRemoveReaction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRemoveReaction.setText("Remove Selected Reaction");
        jButtonRemoveReaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveReactionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 198, Short.MAX_VALUE)
                                .addComponent(jButtonBack))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRemoveReaction)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButtonBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTitle)
                            .addComponent(jButtonRemoveReaction))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Back button
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.databaseGUI.startHomePage();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    //Remove Selected Reaction button
    private void jButtonRemoveReactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveReactionActionPerformed
        if (this.databaseGUI.removeReaction(this.jTableReactions.getSelectedRow())) {
            this.start(this);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonRemoveReactionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRemoveReaction;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReactions;
    // End of variables declaration//GEN-END:variables
}