package gui;

import databaserunner.*;
import javax.swing.*;
import java.awt.event.*;

public class AddElement extends javax.swing.JFrame implements WindowListener {

    //our fields
    private DatabaseGUI databaseGUI;
    
    /**
     * Creates new form AddElement
     */
    public AddElement(DatabaseGUI databaseGUI) {
        this.databaseGUI = databaseGUI;
        this.initComponents(); 
    }

    public void start(AddElement addElement) {
        this.initConstants();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addElement.setVisible(true);
            }
        });
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        if (DatabaseGUI.getMadeChanges()) {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            this.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    databaseGUI.savePrompt(true);
                }
            });
        }
    }
    
    private void initConstants() {
        this.jLabelCommonName.setText(DatabaseGUI.REQUIRED_FIELD_SYMBOL + Chemical.LABEL_NAME + DatabaseGUI.ASSIGNMENT_PUNCTUATION);
        this.jLabelAtomicSymbol.setText(DatabaseGUI.REQUIRED_FIELD_SYMBOL + Element.LABEL_ATOMIC_SYMBOL + DatabaseGUI.ASSIGNMENT_PUNCTUATION);
        this.jLabelNumProton.setText(DatabaseGUI.REQUIRED_FIELD_SYMBOL + NuclearProperties.LABEL_PROTONS + DatabaseGUI.ASSIGNMENT_PUNCTUATION);
        this.jLabelElectronegativity.setText(DatabaseGUI.REQUIRED_FIELD_SYMBOL + NuclearProperties.LABEL_ELECTRONEGATIVITY + DatabaseGUI.ASSIGNMENT_PUNCTUATION);
        this.jLabelNumNeutron.setText(NuclearProperties.LABEL_NEUTRONS + DatabaseGUI.ASSIGNMENT_PUNCTUATION);
        this.jLabelIonizationEnergy.setText(NuclearProperties.LABEL_IONIZATION_ENERGY + DatabaseGUI.ASSIGNMENT_PUNCTUATION);
        this.jLabelStpDensity.setText(Chemical.LABEL_STP_DENSITY + Chemical.LABEL_DENSITY_UNIT + DatabaseGUI.ASSIGNMENT_PUNCTUATION);
        this.jLabelMolarMass.setText(Chemical.LABEL_MOLAR_MASS + Chemical.LABEL_MOLAR_MASS_UNIT + DatabaseGUI.ASSIGNMENT_PUNCTUATION);
        this.jLabelBP.setText(Chemical.LABEL_BP + Chemical.LABEL_STATE_CHANGE_UNIT + DatabaseGUI.ASSIGNMENT_PUNCTUATION);
        this.jLabelMP.setText(Chemical.LABEL_MP + Chemical.LABEL_STATE_CHANGE_UNIT + DatabaseGUI.ASSIGNMENT_PUNCTUATION);
        this.jLabelColour.setText(Chemical.LABEL_COLOUR + DatabaseGUI.ASSIGNMENT_PUNCTUATION);
        
        this.jTextFieldCommonName.setText(DatabaseGUI.EMPTY_STRING);
        this.jTextFieldAtomicSymbol.setText(DatabaseGUI.EMPTY_STRING);
        this.jTextFieldNumProton.setText(DatabaseGUI.EMPTY_STRING);
        this.jTextFieldElectronegativity.setText(DatabaseGUI.EMPTY_STRING);
        this.jTextFieldNumNeutron.setText(DatabaseGUI.EMPTY_STRING);
        this.jTextFieldIonizationEnergy.setText(DatabaseGUI.EMPTY_STRING);
        this.jTextFieldStpDensity.setText(DatabaseGUI.EMPTY_STRING);
        this.jTextFieldMolarMass.setText(DatabaseGUI.EMPTY_STRING);
        this.jTextFieldBP.setText(DatabaseGUI.EMPTY_STRING);
        this.jTextFieldMP.setText(DatabaseGUI.EMPTY_STRING);
        this.jTextFieldColour.setText(DatabaseGUI.EMPTY_STRING);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeTitle = new javax.swing.JLabel();
        jLabelCommonName = new javax.swing.JLabel();
        jLabelStpDensity = new javax.swing.JLabel();
        jLabelMolarMass = new javax.swing.JLabel();
        jLabelBP = new javax.swing.JLabel();
        jLabelMP = new javax.swing.JLabel();
        jLabelColour = new javax.swing.JLabel();
        jLabelNumProton = new javax.swing.JLabel();
        jLabelNumNeutron = new javax.swing.JLabel();
        jLabelIonizationEnergy = new javax.swing.JLabel();
        jLabelElectronegativity = new javax.swing.JLabel();
        jLabelAtomicSymbol = new javax.swing.JLabel();
        jTextFieldCommonName = new javax.swing.JTextField();
        jTextFieldAtomicSymbol = new javax.swing.JTextField();
        jTextFieldNumProton = new javax.swing.JTextField();
        jTextFieldNumNeutron = new javax.swing.JTextField();
        jTextFieldStpDensity = new javax.swing.JTextField();
        jTextFieldMolarMass = new javax.swing.JTextField();
        jTextFieldBP = new javax.swing.JTextField();
        jTextFieldMP = new javax.swing.JTextField();
        jTextFieldColour = new javax.swing.JTextField();
        jTextFieldIonizationEnergy = new javax.swing.JTextField();
        jTextFieldElectronegativity = new javax.swing.JTextField();
        jLabelInfo = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabeTitle.setText("Add Element");

        jLabelCommonName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCommonName.setText("*Name:");

        jLabelStpDensity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelStpDensity.setText("Density @ STP (g/L):");

        jLabelMolarMass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMolarMass.setText("Molar Mass (g/mol):");

        jLabelBP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBP.setText("Boiling Point (C):");

        jLabelMP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMP.setText("Melting Point (C):");

        jLabelColour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelColour.setText("Colour:");

        jLabelNumProton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumProton.setText("*Atomic #");

        jLabelNumNeutron.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumNeutron.setText("Neutrons:");

        jLabelIonizationEnergy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIonizationEnergy.setText("Ionization Energy:");

        jLabelElectronegativity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelElectronegativity.setText("*Electronegativity:");

        jLabelAtomicSymbol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAtomicSymbol.setText("*Atomic Symbol:");

        jTextFieldCommonName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldAtomicSymbol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldNumProton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldNumNeutron.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldStpDensity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldMolarMass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldBP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldMP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldColour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldIonizationEnergy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldElectronegativity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInfo.setText("* = required fields");

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabeTitle)
                                .addGap(67, 67, 67)
                                .addComponent(jLabelInfo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAtomicSymbol)
                                    .addComponent(jLabelCommonName))
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAtomicSymbol, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCommonName)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelIonizationEnergy)
                                    .addComponent(jLabelColour)
                                    .addComponent(jLabelMP)
                                    .addComponent(jLabelBP)
                                    .addComponent(jLabelMolarMass)
                                    .addComponent(jLabelStpDensity)
                                    .addComponent(jLabelNumNeutron))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldIonizationEnergy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(jTextFieldColour, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMolarMass, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldStpDensity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNumNeutron, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNumProton)
                                    .addComponent(jLabelElectronegativity))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNumProton)
                                    .addComponent(jTextFieldElectronegativity))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSubmit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeTitle)
                            .addComponent(jLabelInfo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCommonName)
                            .addComponent(jTextFieldCommonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAtomicSymbol)
                            .addComponent(jTextFieldAtomicSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumProton)
                            .addComponent(jTextFieldNumProton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelElectronegativity)
                            .addComponent(jTextFieldElectronegativity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumNeutron)
                            .addComponent(jTextFieldNumNeutron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStpDensity)
                            .addComponent(jTextFieldStpDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMolarMass)
                            .addComponent(jTextFieldMolarMass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBP)
                            .addComponent(jTextFieldBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMP)
                            .addComponent(jTextFieldMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelColour)
                            .addComponent(jTextFieldColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIonizationEnergy)
                            .addComponent(jTextFieldIonizationEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButtonSubmit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //SUBMIT button
    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        //declare variables
        String commonName;
        String atomicSymbol;
        int numProton;
        int numNeutron;
        double stpDensity;
        double molarMass;
        double bp;
        double mp;
        String colour;
        double ionizationEnergy;
        double electronegativity;
        
        try{
            //read required fields
            commonName = this.jTextFieldCommonName.getText();
            atomicSymbol = this.jTextFieldAtomicSymbol.getText();
            numProton = Integer.parseInt(this.jTextFieldNumProton.getText());
            electronegativity = Double.parseDouble(this.jTextFieldElectronegativity.getText());
            
            //read optional fields
            if(!this.jTextFieldNumNeutron.getText().equals(DatabaseGUI.EMPTY_STRING)){
                numNeutron = Integer.parseInt(this.jTextFieldNumNeutron.getText());
            }else
                numNeutron = NuclearProperties.DEFAULT_NEUTRONS;
            
            if(!this.jTextFieldStpDensity.getText().equals(DatabaseGUI.EMPTY_STRING)){
                stpDensity = Double.parseDouble(this.jTextFieldStpDensity.getText());
            }else
                stpDensity = Chemical.DEFAULT_DENSITY;
            
            if(!this.jTextFieldMolarMass.getText().equals(DatabaseGUI.EMPTY_STRING)){
                molarMass = Double.parseDouble(this.jTextFieldMolarMass.getText());
            }else
                molarMass = Chemical.DEFAULT_MOLAR_MASS;
            
            if(!this.jTextFieldBP.getText().equals(DatabaseGUI.EMPTY_STRING)){
                bp = Double.parseDouble(this.jTextFieldBP.getText());
            }else
                bp = Chemical.DEFAULT_STATE_CHANGE_TEMP;
            
            if(!this.jTextFieldMP.getText().equals(DatabaseGUI.EMPTY_STRING)){
                mp = Double.parseDouble(this.jTextFieldMP.getText());
            }else
                mp = Chemical.DEFAULT_STATE_CHANGE_TEMP;
            
            if(!this.jTextFieldColour.getText().equals(DatabaseGUI.EMPTY_STRING))
                colour = this.jTextFieldColour.getText();
            else
                colour = Chemical.DEFAULT_COLOUR;
            
            if(!this.jTextFieldIonizationEnergy.getText().equals(DatabaseGUI.EMPTY_STRING)){
                ionizationEnergy = Double.parseDouble(this.jTextFieldIonizationEnergy.getText());
            }else
                ionizationEnergy = NuclearProperties.DEFAULT_IONIZATION_ENERGY;
            
            //create new Element and add it to the database ONLY IF properties pass all checks
            Element newElement = new Element(commonName, stpDensity, molarMass, bp, mp, colour, numProton, numNeutron, ionizationEnergy, electronegativity, atomicSymbol);
            
            if(this.jTextFieldCommonName.getText().equals(DatabaseGUI.EMPTY_STRING) || this.jTextFieldAtomicSymbol.getText().equals(DatabaseGUI.EMPTY_STRING) || this.jTextFieldNumProton.getText().equals(DatabaseGUI.EMPTY_STRING) || this.jTextFieldElectronegativity.getText().equals(DatabaseGUI.EMPTY_STRING))
                JOptionPane.showMessageDialog(null, DatabaseGUI.REQUIRED_FIELD + DatabaseGUI.ERROR_FIELD_EMPTY);
            
            else if(!newElement.setCommonName(commonName))
                JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_ILLEGAL_DATA + Chemical.LABEL_NAME.toLowerCase());
            
            else if(commonName.length() > DatabaseGUI.MAXIMUM_STRING_LENGTH)
                JOptionPane.showMessageDialog(null, Chemical.LABEL_NAME + DatabaseGUI.ERROR_TOO_LONG);
            
            else if(!newElement.setAtomicSymbol(atomicSymbol))
                JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_ILLEGAL_DATA + Element.LABEL_ATOMIC_SYMBOL.toLowerCase());
            
            else if(atomicSymbol.length() > DatabaseGUI.MAXIMUM_ATOMIC_SYMBOL_LENGTH)
                JOptionPane.showMessageDialog(null, Element.LABEL_ATOMIC_SYMBOL + DatabaseGUI.ERROR_TOO_LONG);
            
            else if(!newElement.setNumProton(numProton))
                JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_ILLEGAL_DATA + NuclearProperties.LABEL_PROTONS.toLowerCase());
            
            else if(!newElement.setElectronegativity(electronegativity))
                JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_ILLEGAL_DATA + NuclearProperties.LABEL_ELECTRONEGATIVITY.toLowerCase());
            
            else if(!newElement.setNumNeutron(numNeutron))
                JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_ILLEGAL_DATA + NuclearProperties.LABEL_NEUTRONS.toLowerCase());
            
            else if(!newElement.setStpDensity(stpDensity))
                JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_ILLEGAL_DATA + Chemical.LABEL_STP_DENSITY.toLowerCase());
            
            else if(!newElement.setMolarMass(molarMass))
                JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_ILLEGAL_DATA + Chemical.LABEL_MOLAR_MASS.toLowerCase());
            
            else if(!newElement.setBP(bp))
                JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_ILLEGAL_DATA + Chemical.LABEL_BP.toLowerCase());
            
            else if(!newElement.setMP(mp))
                JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_ILLEGAL_DATA + Chemical.LABEL_MP.toLowerCase());
            
            else if(!newElement.setIonizationEnergy(ionizationEnergy))
                JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_ILLEGAL_DATA + NuclearProperties.LABEL_IONIZATION_ENERGY.toLowerCase());
            
            else if(colour.length() > DatabaseGUI.MAXIMUM_STRING_LENGTH)
                JOptionPane.showMessageDialog(null, Chemical.LABEL_COLOUR + DatabaseGUI.ERROR_TOO_LONG);
            
            else if(this.databaseGUI.addElement(newElement)){
                this.databaseGUI.startHomePage();
                this.setVisible(false);
                
            }else
                JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_REPEAT);
            
        }catch(NumberFormatException nfx){
            JOptionPane.showMessageDialog(null, DatabaseGUI.ERROR_ERRONEOUS_DATA);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    //Back button
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.databaseGUI.startHomePage();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabeTitle;
    private javax.swing.JLabel jLabelAtomicSymbol;
    private javax.swing.JLabel jLabelBP;
    private javax.swing.JLabel jLabelColour;
    private javax.swing.JLabel jLabelCommonName;
    private javax.swing.JLabel jLabelElectronegativity;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelIonizationEnergy;
    private javax.swing.JLabel jLabelMP;
    private javax.swing.JLabel jLabelMolarMass;
    private javax.swing.JLabel jLabelNumNeutron;
    private javax.swing.JLabel jLabelNumProton;
    private javax.swing.JLabel jLabelStpDensity;
    private javax.swing.JTextField jTextFieldAtomicSymbol;
    private javax.swing.JTextField jTextFieldBP;
    private javax.swing.JTextField jTextFieldColour;
    private javax.swing.JTextField jTextFieldCommonName;
    private javax.swing.JTextField jTextFieldElectronegativity;
    private javax.swing.JTextField jTextFieldIonizationEnergy;
    private javax.swing.JTextField jTextFieldMP;
    private javax.swing.JTextField jTextFieldMolarMass;
    private javax.swing.JTextField jTextFieldNumNeutron;
    private javax.swing.JTextField jTextFieldNumProton;
    private javax.swing.JTextField jTextFieldStpDensity;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosing(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosed(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}